### ISSUE TITLE
[crash] panic/out-of-memory when deserializing Blockdata structures

### ISSUE THREAD

**Issue by pventuzelo** [monero-rs/monero-rs#46]
Hey, 

I just found this panic/OOM bug when fuzzing Block deserialization.
Depending on the data provided, you can either trigger a panic throw by the `alloc` library or you will directly trigger an OOM. 

affected version: 0.13.0

# `capacity overflow` panic

Code:
``` rust
fn panic_alloc_capacity_overflow_MoneroBlock_deserialize() {
    let data = [
        0x0f, 0x9e, 0xa5, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x04, 0x00, 0x08, 0x9e, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x04, 0x9e, 0x9e,
        0x9e, 0x9e, 0x9e, 0x9e, 0x9e, 0x9e, 0x9e, 0xe7, 0xaa, 0xfd, 0x8b, 0x47, 0x06, 0x8d, 0xed,
        0xe3, 0x00, 0xed, 0x44, 0xfc, 0x77, 0xd6, 0x58, 0xf6, 0xf2, 0x69, 0x06, 0x8d, 0xed, 0xe3,
        0x00, 0xed, 0x44, 0xfc, 0x77, 0xd6, 0x58, 0xf6, 0xf2, 0x69, 0x62, 0x38, 0xdb, 0x5e, 0x4d,
        0x6d, 0x9c, 0x94, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x8f, 0x74, 0x3c,
        0xb3, 0x1b, 0x6e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ];
    let _ = deserialize::<Block>(&data);
}
```
Backtrace:
``` sh
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:552:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5
   3: alloc::raw_vec::capacity_overflow
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/raw_vec.rs:552:5
   4: alloc::raw_vec::RawVec<T,A>::allocate_in
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/raw_vec.rs:194:27
   5: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/raw_vec.rs:142:9
   6: alloc::vec::Vec<T,A>::with_capacity_in
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/vec/mod.rs:580:20
   7: alloc::vec::Vec<T>::with_capacity
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/vec/mod.rs:442:9
   8: <alloc::vec::Vec<T> as monero::consensus::encode::Decodable>::consensus_decode
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/monero-0.13.0/src/consensus/encode.rs:452:23
   9: <monero::blockdata::transaction::TransactionPrefix as monero::consensus::encode::Decodable>::consensus_decode
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/monero-0.13.0/src/internal_macros.rs:40:32
  10: <monero::blockdata::transaction::Transaction as monero::consensus::encode::Decodable>::consensus_decode
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/monero-0.13.0/src/blockdata/transaction.rs:765:41
  11: <monero::blockdata::block::Block as monero::consensus::encode::Decodable>::consensus_decode
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/monero-0.13.0/src/internal_macros.rs:40:32
  12: monero::consensus::encode::deserialize_partial
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/monero-0.13.0/src/consensus/encode.rs:94:14
  13: monero::consensus::encode::deserialize
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/monero-0.13.0/src/consensus/encode.rs:78:26
  14: crash_repro::panic_alloc_capacity_overflow_MoneroBlock_deserialize
             at ./src/main.rs:111:13
  15: crash_repro::main
             at ./src/main.rs:129:13
  16: core::ops::function::FnOnce::call_once
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

# Out-of-memory (OOM)

Code:
``` rust
fn oom_MoneroBlock_deserialize() {
    let data = [
        0x09, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x95,
        0x95, 0x95, 0x95, 0x01, 0x00, 0x00, 0x00, 0xc3, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x38, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x95, 0x00, 0x00, 0x00, 0x95, 0x95, 0x95,
        0x95, 0x95, 0x95, 0x95, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x95, 0x95, 0x95,
        0x95, 0x95, 0x95, 0x95,
    ];
    let _ = deserialize::<Block>(&data);
}
```
Crash:
``` sh
memory allocation of 5957517617308992 bytes failed
```

**Comment by sdbondi** [comment]
I've been looking at this. I believe the issue is the Encodable impl of Vec that allocates len elements given as a VarInt without checking the max allowed byte allocation (`isize::MAX`). This also would affect the `String` impl. I'm happy to PR a fix for this.
